//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Recomendation.Web.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS.Recomendation.Web.DataService.CityWeather[] Weather5DaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WS.Recomendation.Web.DataService.CityWeather[] Weather5Days {
            get {
                return this.Weather5DaysField;
            }
            set {
                if ((object.ReferenceEquals(this.Weather5DaysField, value) != true)) {
                    this.Weather5DaysField = value;
                    this.RaisePropertyChanged("Weather5Days");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityWeather", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class CityWeather : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double TemperatureField;
        
        private double HumidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Humidity {
            get {
                return this.HumidityField;
            }
            set {
                if ((this.HumidityField.Equals(value) != true)) {
                    this.HumidityField = value;
                    this.RaisePropertyChanged("Humidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distance", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class Distance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OriginCityIdField;
        
        private int DestinationCityIdField;
        
        private int DistanceInKmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginCityId {
            get {
                return this.OriginCityIdField;
            }
            set {
                if ((this.OriginCityIdField.Equals(value) != true)) {
                    this.OriginCityIdField = value;
                    this.RaisePropertyChanged("OriginCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DestinationCityId {
            get {
                return this.DestinationCityIdField;
            }
            set {
                if ((this.DestinationCityIdField.Equals(value) != true)) {
                    this.DestinationCityIdField = value;
                    this.RaisePropertyChanged("DestinationCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DistanceInKm {
            get {
                return this.DistanceInKmField;
            }
            set {
                if ((this.DistanceInKmField.Equals(value) != true)) {
                    this.DistanceInKmField = value;
                    this.RaisePropertyChanged("DistanceInKm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS.Recomendation.Data.org/", ConfigurationName="DataService.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllCitiesResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllCities", ReplyAction="*")]
        WS.Recomendation.Web.DataService.GetAllCitiesResponse GetAllCities(WS.Recomendation.Web.DataService.GetAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetAllCitiesResponse> GetAllCitiesAsync(WS.Recomendation.Web.DataService.GetAllCitiesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDistancesByOriginCityIdResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByOriginCityId", ReplyAction="*")]
        WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponse GetDistancesByOriginCityId(WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByOriginCityId", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponse> GetDistancesByOriginCityIdAsync(WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDistancesByDestinationCityIdResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByDestinationCityId", ReplyAction="*")]
        WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponse GetDistancesByDestinationCityId(WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByDestinationCityId", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponse> GetDistancesByDestinationCityIdAsync(WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCities", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Web.DataService.GetAllCitiesRequestBody Body;
        
        public GetAllCitiesRequest() {
        }
        
        public GetAllCitiesRequest(WS.Recomendation.Web.DataService.GetAllCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCitiesRequestBody {
        
        public GetAllCitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCitiesResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Web.DataService.GetAllCitiesResponseBody Body;
        
        public GetAllCitiesResponse() {
        }
        
        public GetAllCitiesResponse(WS.Recomendation.Web.DataService.GetAllCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetAllCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Web.DataService.City[] GetAllCitiesResult;
        
        public GetAllCitiesResponseBody() {
        }
        
        public GetAllCitiesResponseBody(WS.Recomendation.Web.DataService.City[] GetAllCitiesResult) {
            this.GetAllCitiesResult = GetAllCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByOriginCityIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByOriginCityId", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequestBody Body;
        
        public GetDistancesByOriginCityIdRequest() {
        }
        
        public GetDistancesByOriginCityIdRequest(WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByOriginCityIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int originCityId;
        
        public GetDistancesByOriginCityIdRequestBody() {
        }
        
        public GetDistancesByOriginCityIdRequestBody(int originCityId) {
            this.originCityId = originCityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByOriginCityIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByOriginCityIdResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponseBody Body;
        
        public GetDistancesByOriginCityIdResponse() {
        }
        
        public GetDistancesByOriginCityIdResponse(WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByOriginCityIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Web.DataService.Distance[] GetDistancesByOriginCityIdResult;
        
        public GetDistancesByOriginCityIdResponseBody() {
        }
        
        public GetDistancesByOriginCityIdResponseBody(WS.Recomendation.Web.DataService.Distance[] GetDistancesByOriginCityIdResult) {
            this.GetDistancesByOriginCityIdResult = GetDistancesByOriginCityIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByDestinationCityIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByDestinationCityId", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequestBody Body;
        
        public GetDistancesByDestinationCityIdRequest() {
        }
        
        public GetDistancesByDestinationCityIdRequest(WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByDestinationCityIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int originCityId;
        
        public GetDistancesByDestinationCityIdRequestBody() {
        }
        
        public GetDistancesByDestinationCityIdRequestBody(int originCityId) {
            this.originCityId = originCityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByDestinationCityIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByDestinationCityIdResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponseBody Body;
        
        public GetDistancesByDestinationCityIdResponse() {
        }
        
        public GetDistancesByDestinationCityIdResponse(WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByDestinationCityIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Web.DataService.Distance[] GetDistancesByDestinationCityIdResult;
        
        public GetDistancesByDestinationCityIdResponseBody() {
        }
        
        public GetDistancesByDestinationCityIdResponseBody(WS.Recomendation.Web.DataService.Distance[] GetDistancesByDestinationCityIdResult) {
            this.GetDistancesByDestinationCityIdResult = GetDistancesByDestinationCityIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : WS.Recomendation.Web.DataService.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<WS.Recomendation.Web.DataService.DataServiceSoap>, WS.Recomendation.Web.DataService.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Web.DataService.GetAllCitiesResponse WS.Recomendation.Web.DataService.DataServiceSoap.GetAllCities(WS.Recomendation.Web.DataService.GetAllCitiesRequest request) {
            return base.Channel.GetAllCities(request);
        }
        
        public WS.Recomendation.Web.DataService.City[] GetAllCities() {
            WS.Recomendation.Web.DataService.GetAllCitiesRequest inValue = new WS.Recomendation.Web.DataService.GetAllCitiesRequest();
            inValue.Body = new WS.Recomendation.Web.DataService.GetAllCitiesRequestBody();
            WS.Recomendation.Web.DataService.GetAllCitiesResponse retVal = ((WS.Recomendation.Web.DataService.DataServiceSoap)(this)).GetAllCities(inValue);
            return retVal.Body.GetAllCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetAllCitiesResponse> WS.Recomendation.Web.DataService.DataServiceSoap.GetAllCitiesAsync(WS.Recomendation.Web.DataService.GetAllCitiesRequest request) {
            return base.Channel.GetAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetAllCitiesResponse> GetAllCitiesAsync() {
            WS.Recomendation.Web.DataService.GetAllCitiesRequest inValue = new WS.Recomendation.Web.DataService.GetAllCitiesRequest();
            inValue.Body = new WS.Recomendation.Web.DataService.GetAllCitiesRequestBody();
            return ((WS.Recomendation.Web.DataService.DataServiceSoap)(this)).GetAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponse WS.Recomendation.Web.DataService.DataServiceSoap.GetDistancesByOriginCityId(WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest request) {
            return base.Channel.GetDistancesByOriginCityId(request);
        }
        
        public WS.Recomendation.Web.DataService.Distance[] GetDistancesByOriginCityId(int originCityId) {
            WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest inValue = new WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest();
            inValue.Body = new WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponse retVal = ((WS.Recomendation.Web.DataService.DataServiceSoap)(this)).GetDistancesByOriginCityId(inValue);
            return retVal.Body.GetDistancesByOriginCityIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponse> WS.Recomendation.Web.DataService.DataServiceSoap.GetDistancesByOriginCityIdAsync(WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest request) {
            return base.Channel.GetDistancesByOriginCityIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdResponse> GetDistancesByOriginCityIdAsync(int originCityId) {
            WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest inValue = new WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequest();
            inValue.Body = new WS.Recomendation.Web.DataService.GetDistancesByOriginCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            return ((WS.Recomendation.Web.DataService.DataServiceSoap)(this)).GetDistancesByOriginCityIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponse WS.Recomendation.Web.DataService.DataServiceSoap.GetDistancesByDestinationCityId(WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest request) {
            return base.Channel.GetDistancesByDestinationCityId(request);
        }
        
        public WS.Recomendation.Web.DataService.Distance[] GetDistancesByDestinationCityId(int originCityId) {
            WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest inValue = new WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest();
            inValue.Body = new WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponse retVal = ((WS.Recomendation.Web.DataService.DataServiceSoap)(this)).GetDistancesByDestinationCityId(inValue);
            return retVal.Body.GetDistancesByDestinationCityIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponse> WS.Recomendation.Web.DataService.DataServiceSoap.GetDistancesByDestinationCityIdAsync(WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest request) {
            return base.Channel.GetDistancesByDestinationCityIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdResponse> GetDistancesByDestinationCityIdAsync(int originCityId) {
            WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest inValue = new WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequest();
            inValue.Body = new WS.Recomendation.Web.DataService.GetDistancesByDestinationCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            return ((WS.Recomendation.Web.DataService.DataServiceSoap)(this)).GetDistancesByDestinationCityIdAsync(inValue);
        }
    }
}
