//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Recomendation.Data {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WS.Recomendation.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Albacete,Alicante,Almería,Ávila,Badajoz,Barcelona,Bilbao,Burgos,Cáceres,Cádiz,Castellón,Ciudad Real,Córdoba,A Coruña,Cuenca,Gerona,Granada,Guadalajara,Huelva,Huesca,Jaén,León,Lérida,Logroño,Lugo,Madrid,Málaga,Murcia,Orense,Oviedo,Palencia,Pamplona,Pontevedra,Salamanca,San Sebastian,Santander,Segovia,Sevilla,Soria,Tarragona,Teruel,Toledo,Valencia,Valladolid,Vitoria,Zamora,Zaragoza.
        /// </summary>
        internal static string cities_array {
            get {
                return ResourceManager.GetString("cities_array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 0,171,369,366,525,540,646,488,504,617,256,207,354,860,142,640,363,309,506,495,264,584,515,578,762,251,473,150,772,702,491,598,874,463,691,644,338,492,473,443,242,240,191,444,602,499,423
        ///171,0,294,537,696,515,817,659,675,688,231,378,525,1031,313,615,353,480,703,570,415,855,490,653,933,422,482,75,943,873,662,673,1045,634,766,815,509,609,548,417,317,411,166,615,739,670,498
        ///369,294,0,663,604,809,958,800,651,484,525,407,332,1172,511,909,166,621,516,830,228,896,802,899,1074,563,219,219,1084,1014,803,970,1186,763, [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string distance_matrix {
            get {
                return ResourceManager.GetString("distance_matrix", resourceCulture);
            }
        }
    }
}
