
package ws.recomendation.webservices.services.cities;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CitiesServiceSoap", targetNamespace = "http://WS.Recomendation.Cities/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CitiesServiceSoap {


    /**
     * 
     * @param numberOfCitiesToReturn
     * @param originCityId
     * @return
     *     returns ws.recomendation.webservices.services.cities.ArrayOfCity
     */
    @WebMethod(operationName = "GetClosestCities", action = "http://WS.Recomendation.Cities/GetClosestCities")
    @WebResult(name = "GetClosestCitiesResult", targetNamespace = "http://WS.Recomendation.Cities/")
    @RequestWrapper(localName = "GetClosestCities", targetNamespace = "http://WS.Recomendation.Cities/", className = "ws.recomendation.webservices.services.cities.GetClosestCities")
    @ResponseWrapper(localName = "GetClosestCitiesResponse", targetNamespace = "http://WS.Recomendation.Cities/", className = "ws.recomendation.webservices.services.cities.GetClosestCitiesResponse")
    public ArrayOfCity getClosestCities(
        @WebParam(name = "originCityId", targetNamespace = "http://WS.Recomendation.Cities/")
        int originCityId,
        @WebParam(name = "numberOfCitiesToReturn", targetNamespace = "http://WS.Recomendation.Cities/")
        int numberOfCitiesToReturn);

    /**
     * 
     * @param numberOfCitiesToReturn
     * @param originCityId
     * @return
     *     returns ws.recomendation.webservices.services.cities.ArrayOfCity
     */
    @WebMethod(operationName = "GetClosestCitiesWithWeatcher", action = "http://WS.Recomendation.Cities/GetClosestCitiesWithWeatcher")
    @WebResult(name = "GetClosestCitiesWithWeatcherResult", targetNamespace = "http://WS.Recomendation.Cities/")
    @RequestWrapper(localName = "GetClosestCitiesWithWeatcher", targetNamespace = "http://WS.Recomendation.Cities/", className = "ws.recomendation.webservices.services.cities.GetClosestCitiesWithWeatcher")
    @ResponseWrapper(localName = "GetClosestCitiesWithWeatcherResponse", targetNamespace = "http://WS.Recomendation.Cities/", className = "ws.recomendation.webservices.services.cities.GetClosestCitiesWithWeatcherResponse")
    public ArrayOfCity getClosestCitiesWithWeatcher(
        @WebParam(name = "originCityId", targetNamespace = "http://WS.Recomendation.Cities/")
        int originCityId,
        @WebParam(name = "numberOfCitiesToReturn", targetNamespace = "http://WS.Recomendation.Cities/")
        int numberOfCitiesToReturn);

}
