//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS.Recomendation.Authentication.ServiceData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class City : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.Nullable<double> LatitudeField;
        
        private System.Nullable<double> LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WS.Recomendation.Authentication.ServiceData.CityWeather[] Weather5DaysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<double> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<double> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WS.Recomendation.Authentication.ServiceData.CityWeather[] Weather5Days {
            get {
                return this.Weather5DaysField;
            }
            set {
                if ((object.ReferenceEquals(this.Weather5DaysField, value) != true)) {
                    this.Weather5DaysField = value;
                    this.RaisePropertyChanged("Weather5Days");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityWeather", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class CityWeather : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double TemperatureField;
        
        private double HumidityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Temperature {
            get {
                return this.TemperatureField;
            }
            set {
                if ((this.TemperatureField.Equals(value) != true)) {
                    this.TemperatureField = value;
                    this.RaisePropertyChanged("Temperature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Humidity {
            get {
                return this.HumidityField;
            }
            set {
                if ((this.HumidityField.Equals(value) != true)) {
                    this.HumidityField = value;
                    this.RaisePropertyChanged("Humidity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distance", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class Distance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OriginCityIdField;
        
        private int DestinationCityIdField;
        
        private int DistanceInKmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginCityId {
            get {
                return this.OriginCityIdField;
            }
            set {
                if ((this.OriginCityIdField.Equals(value) != true)) {
                    this.OriginCityIdField = value;
                    this.RaisePropertyChanged("OriginCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DestinationCityId {
            get {
                return this.DestinationCityIdField;
            }
            set {
                if ((this.DestinationCityIdField.Equals(value) != true)) {
                    this.DestinationCityIdField = value;
                    this.RaisePropertyChanged("DestinationCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DistanceInKm {
            get {
                return this.DistanceInKmField;
            }
            set {
                if ((this.DistanceInKmField.Equals(value) != true)) {
                    this.DistanceInKmField = value;
                    this.RaisePropertyChanged("DistanceInKm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FavCities", Namespace="http://WS.Recomendation.Data.org/")]
    [System.SerializableAttribute()]
    public partial class FavCities : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OriginCityIdField;
        
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OriginCityId {
            get {
                return this.OriginCityIdField;
            }
            set {
                if ((this.OriginCityIdField.Equals(value) != true)) {
                    this.OriginCityIdField = value;
                    this.RaisePropertyChanged("OriginCityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS.Recomendation.Data.org/", ConfigurationName="ServiceData.DataServiceSoap")]
    public interface DataServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllCitiesResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllCities", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponse GetAllCities(WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponse> GetAllCitiesAsync(WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDistancesByOriginCityIdResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByOriginCityId", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponse GetDistancesByOriginCityId(WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByOriginCityId", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponse> GetDistancesByOriginCityIdAsync(WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDistancesByDestinationCityIdResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByDestinationCityId", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponse GetDistancesByDestinationCityId(WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetDistancesByDestinationCityId", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponse> GetDistancesByDestinationCityIdAsync(WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllUsersResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllUsers", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.GetAllUsersResponse GetAllUsers(WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllUsersResponse> GetAllUsersAsync(WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllFavCitiesResult del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllFavCities", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponse GetAllFavCities(WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetAllFavCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponse> GetAllFavCitiesAsync(WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/ExistUser", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.ExistUserResponse ExistUser(WS.Recomendation.Authentication.ServiceData.ExistUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/ExistUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.ExistUserResponse> ExistUserAsync(WS.Recomendation.Authentication.ServiceData.ExistUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/AddUser", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.AddUserResponse AddUser(WS.Recomendation.Authentication.ServiceData.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.AddUserResponse> AddUserAsync(WS.Recomendation.Authentication.ServiceData.AddUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento favCities del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/AddFavCities", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponse AddFavCities(WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/AddFavCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponse> AddFavCitiesAsync(WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/UpdateUser", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.UpdateUserResponse UpdateUser(WS.Recomendation.Authentication.ServiceData.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.UpdateUserResponse> UpdateUserAsync(WS.Recomendation.Authentication.ServiceData.UpdateUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://WS.Recomendation.Data.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetUserByName", ReplyAction="*")]
        WS.Recomendation.Authentication.ServiceData.GetUserByNameResponse GetUserByName(WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.Recomendation.Data.org/GetUserByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetUserByNameResponse> GetUserByNameAsync(WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCities", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequestBody Body;
        
        public GetAllCitiesRequest() {
        }
        
        public GetAllCitiesRequest(WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCitiesRequestBody {
        
        public GetAllCitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCitiesResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponseBody Body;
        
        public GetAllCitiesResponse() {
        }
        
        public GetAllCitiesResponse(WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetAllCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.City[] GetAllCitiesResult;
        
        public GetAllCitiesResponseBody() {
        }
        
        public GetAllCitiesResponseBody(WS.Recomendation.Authentication.ServiceData.City[] GetAllCitiesResult) {
            this.GetAllCitiesResult = GetAllCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByOriginCityIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByOriginCityId", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequestBody Body;
        
        public GetDistancesByOriginCityIdRequest() {
        }
        
        public GetDistancesByOriginCityIdRequest(WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByOriginCityIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int originCityId;
        
        public GetDistancesByOriginCityIdRequestBody() {
        }
        
        public GetDistancesByOriginCityIdRequestBody(int originCityId) {
            this.originCityId = originCityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByOriginCityIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByOriginCityIdResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponseBody Body;
        
        public GetDistancesByOriginCityIdResponse() {
        }
        
        public GetDistancesByOriginCityIdResponse(WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByOriginCityIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.Distance[] GetDistancesByOriginCityIdResult;
        
        public GetDistancesByOriginCityIdResponseBody() {
        }
        
        public GetDistancesByOriginCityIdResponseBody(WS.Recomendation.Authentication.ServiceData.Distance[] GetDistancesByOriginCityIdResult) {
            this.GetDistancesByOriginCityIdResult = GetDistancesByOriginCityIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByDestinationCityIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByDestinationCityId", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequestBody Body;
        
        public GetDistancesByDestinationCityIdRequest() {
        }
        
        public GetDistancesByDestinationCityIdRequest(WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByDestinationCityIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int originCityId;
        
        public GetDistancesByDestinationCityIdRequestBody() {
        }
        
        public GetDistancesByDestinationCityIdRequestBody(int originCityId) {
            this.originCityId = originCityId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistancesByDestinationCityIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistancesByDestinationCityIdResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponseBody Body;
        
        public GetDistancesByDestinationCityIdResponse() {
        }
        
        public GetDistancesByDestinationCityIdResponse(WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetDistancesByDestinationCityIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.Distance[] GetDistancesByDestinationCityIdResult;
        
        public GetDistancesByDestinationCityIdResponseBody() {
        }
        
        public GetDistancesByDestinationCityIdResponseBody(WS.Recomendation.Authentication.ServiceData.Distance[] GetDistancesByDestinationCityIdResult) {
            this.GetDistancesByDestinationCityIdResult = GetDistancesByDestinationCityIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(WS.Recomendation.Authentication.ServiceData.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(WS.Recomendation.Authentication.ServiceData.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.User[] GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(WS.Recomendation.Authentication.ServiceData.User[] GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFavCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFavCities", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequestBody Body;
        
        public GetAllFavCitiesRequest() {
        }
        
        public GetAllFavCitiesRequest(WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllFavCitiesRequestBody {
        
        public GetAllFavCitiesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllFavCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllFavCitiesResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponseBody Body;
        
        public GetAllFavCitiesResponse() {
        }
        
        public GetAllFavCitiesResponse(WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetAllFavCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.FavCities[] GetAllFavCitiesResult;
        
        public GetAllFavCitiesResponseBody() {
        }
        
        public GetAllFavCitiesResponseBody(WS.Recomendation.Authentication.ServiceData.FavCities[] GetAllFavCitiesResult) {
            this.GetAllFavCitiesResult = GetAllFavCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistUser", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.ExistUserRequestBody Body;
        
        public ExistUserRequest() {
        }
        
        public ExistUserRequest(WS.Recomendation.Authentication.ServiceData.ExistUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class ExistUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ExistUserRequestBody() {
        }
        
        public ExistUserRequestBody(string name, string password) {
            this.name = name;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistUserResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.ExistUserResponseBody Body;
        
        public ExistUserResponse() {
        }
        
        public ExistUserResponse(WS.Recomendation.Authentication.ServiceData.ExistUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class ExistUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistUserResult;
        
        public ExistUserResponseBody() {
        }
        
        public ExistUserResponseBody(bool ExistUserResult) {
            this.ExistUserResult = ExistUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(WS.Recomendation.Authentication.ServiceData.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.User user;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(WS.Recomendation.Authentication.ServiceData.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(WS.Recomendation.Authentication.ServiceData.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddUserResponseBody {
        
        public AddUserResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFavCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFavCities", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequestBody Body;
        
        public AddFavCitiesRequest() {
        }
        
        public AddFavCitiesRequest(WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class AddFavCitiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.FavCities favCities;
        
        public AddFavCitiesRequestBody() {
        }
        
        public AddFavCitiesRequestBody(WS.Recomendation.Authentication.ServiceData.FavCities favCities) {
            this.favCities = favCities;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFavCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddFavCitiesResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponseBody Body;
        
        public AddFavCitiesResponse() {
        }
        
        public AddFavCitiesResponse(WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddFavCitiesResponseBody {
        
        public AddFavCitiesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(WS.Recomendation.Authentication.ServiceData.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.User user;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(WS.Recomendation.Authentication.ServiceData.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(WS.Recomendation.Authentication.ServiceData.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(bool UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByName", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetUserByNameRequestBody Body;
        
        public GetUserByNameRequest() {
        }
        
        public GetUserByNameRequest(WS.Recomendation.Authentication.ServiceData.GetUserByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetUserByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetUserByNameRequestBody() {
        }
        
        public GetUserByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserByNameResponse", Namespace="http://WS.Recomendation.Data.org/", Order=0)]
        public WS.Recomendation.Authentication.ServiceData.GetUserByNameResponseBody Body;
        
        public GetUserByNameResponse() {
        }
        
        public GetUserByNameResponse(WS.Recomendation.Authentication.ServiceData.GetUserByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://WS.Recomendation.Data.org/")]
    public partial class GetUserByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS.Recomendation.Authentication.ServiceData.User GetUserByNameResult;
        
        public GetUserByNameResponseBody() {
        }
        
        public GetUserByNameResponseBody(WS.Recomendation.Authentication.ServiceData.User GetUserByNameResult) {
            this.GetUserByNameResult = GetUserByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceSoapChannel : WS.Recomendation.Authentication.ServiceData.DataServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceSoapClient : System.ServiceModel.ClientBase<WS.Recomendation.Authentication.ServiceData.DataServiceSoap>, WS.Recomendation.Authentication.ServiceData.DataServiceSoap {
        
        public DataServiceSoapClient() {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetAllCities(WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest request) {
            return base.Channel.GetAllCities(request);
        }
        
        public WS.Recomendation.Authentication.ServiceData.City[] GetAllCities() {
            WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequestBody();
            WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetAllCities(inValue);
            return retVal.Body.GetAllCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetAllCitiesAsync(WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest request) {
            return base.Channel.GetAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllCitiesResponse> GetAllCitiesAsync() {
            WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetAllCitiesRequestBody();
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetDistancesByOriginCityId(WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest request) {
            return base.Channel.GetDistancesByOriginCityId(request);
        }
        
        public WS.Recomendation.Authentication.ServiceData.Distance[] GetDistancesByOriginCityId(int originCityId) {
            WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetDistancesByOriginCityId(inValue);
            return retVal.Body.GetDistancesByOriginCityIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetDistancesByOriginCityIdAsync(WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest request) {
            return base.Channel.GetDistancesByOriginCityIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdResponse> GetDistancesByOriginCityIdAsync(int originCityId) {
            WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetDistancesByOriginCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetDistancesByOriginCityIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetDistancesByDestinationCityId(WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest request) {
            return base.Channel.GetDistancesByDestinationCityId(request);
        }
        
        public WS.Recomendation.Authentication.ServiceData.Distance[] GetDistancesByDestinationCityId(int originCityId) {
            WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetDistancesByDestinationCityId(inValue);
            return retVal.Body.GetDistancesByDestinationCityIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetDistancesByDestinationCityIdAsync(WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest request) {
            return base.Channel.GetDistancesByDestinationCityIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdResponse> GetDistancesByDestinationCityIdAsync(int originCityId) {
            WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetDistancesByDestinationCityIdRequestBody();
            inValue.Body.originCityId = originCityId;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetDistancesByDestinationCityIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.GetAllUsersResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetAllUsers(WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public WS.Recomendation.Authentication.ServiceData.User[] GetAllUsers() {
            WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetAllUsersRequestBody();
            WS.Recomendation.Authentication.ServiceData.GetAllUsersResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllUsersResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetAllUsersAsync(WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllUsersResponse> GetAllUsersAsync() {
            WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetAllUsersRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetAllUsersRequestBody();
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetAllFavCities(WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest request) {
            return base.Channel.GetAllFavCities(request);
        }
        
        public WS.Recomendation.Authentication.ServiceData.FavCities[] GetAllFavCities() {
            WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequestBody();
            WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetAllFavCities(inValue);
            return retVal.Body.GetAllFavCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetAllFavCitiesAsync(WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest request) {
            return base.Channel.GetAllFavCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesResponse> GetAllFavCitiesAsync() {
            WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetAllFavCitiesRequestBody();
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetAllFavCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.ExistUserResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.ExistUser(WS.Recomendation.Authentication.ServiceData.ExistUserRequest request) {
            return base.Channel.ExistUser(request);
        }
        
        public bool ExistUser(string name, string password) {
            WS.Recomendation.Authentication.ServiceData.ExistUserRequest inValue = new WS.Recomendation.Authentication.ServiceData.ExistUserRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.ExistUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            WS.Recomendation.Authentication.ServiceData.ExistUserResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).ExistUser(inValue);
            return retVal.Body.ExistUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.ExistUserResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.ExistUserAsync(WS.Recomendation.Authentication.ServiceData.ExistUserRequest request) {
            return base.Channel.ExistUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.ExistUserResponse> ExistUserAsync(string name, string password) {
            WS.Recomendation.Authentication.ServiceData.ExistUserRequest inValue = new WS.Recomendation.Authentication.ServiceData.ExistUserRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.ExistUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.password = password;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).ExistUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.AddUserResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.AddUser(WS.Recomendation.Authentication.ServiceData.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public void AddUser(WS.Recomendation.Authentication.ServiceData.User user) {
            WS.Recomendation.Authentication.ServiceData.AddUserRequest inValue = new WS.Recomendation.Authentication.ServiceData.AddUserRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.AddUserRequestBody();
            inValue.Body.user = user;
            WS.Recomendation.Authentication.ServiceData.AddUserResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).AddUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.AddUserResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.AddUserAsync(WS.Recomendation.Authentication.ServiceData.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.AddUserResponse> AddUserAsync(WS.Recomendation.Authentication.ServiceData.User user) {
            WS.Recomendation.Authentication.ServiceData.AddUserRequest inValue = new WS.Recomendation.Authentication.ServiceData.AddUserRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.AddUserRequestBody();
            inValue.Body.user = user;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.AddFavCities(WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest request) {
            return base.Channel.AddFavCities(request);
        }
        
        public void AddFavCities(WS.Recomendation.Authentication.ServiceData.FavCities favCities) {
            WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest inValue = new WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequestBody();
            inValue.Body.favCities = favCities;
            WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).AddFavCities(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.AddFavCitiesAsync(WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest request) {
            return base.Channel.AddFavCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.AddFavCitiesResponse> AddFavCitiesAsync(WS.Recomendation.Authentication.ServiceData.FavCities favCities) {
            WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest inValue = new WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.AddFavCitiesRequestBody();
            inValue.Body.favCities = favCities;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).AddFavCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.UpdateUserResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.UpdateUser(WS.Recomendation.Authentication.ServiceData.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public bool UpdateUser(WS.Recomendation.Authentication.ServiceData.User user) {
            WS.Recomendation.Authentication.ServiceData.UpdateUserRequest inValue = new WS.Recomendation.Authentication.ServiceData.UpdateUserRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.UpdateUserRequestBody();
            inValue.Body.user = user;
            WS.Recomendation.Authentication.ServiceData.UpdateUserResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.UpdateUserResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.UpdateUserAsync(WS.Recomendation.Authentication.ServiceData.UpdateUserRequest request) {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.UpdateUserResponse> UpdateUserAsync(WS.Recomendation.Authentication.ServiceData.User user) {
            WS.Recomendation.Authentication.ServiceData.UpdateUserRequest inValue = new WS.Recomendation.Authentication.ServiceData.UpdateUserRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.UpdateUserRequestBody();
            inValue.Body.user = user;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).UpdateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WS.Recomendation.Authentication.ServiceData.GetUserByNameResponse WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetUserByName(WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest request) {
            return base.Channel.GetUserByName(request);
        }
        
        public WS.Recomendation.Authentication.ServiceData.User GetUserByName(string name) {
            WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetUserByNameRequestBody();
            inValue.Body.name = name;
            WS.Recomendation.Authentication.ServiceData.GetUserByNameResponse retVal = ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetUserByName(inValue);
            return retVal.Body.GetUserByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetUserByNameResponse> WS.Recomendation.Authentication.ServiceData.DataServiceSoap.GetUserByNameAsync(WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest request) {
            return base.Channel.GetUserByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS.Recomendation.Authentication.ServiceData.GetUserByNameResponse> GetUserByNameAsync(string name) {
            WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest inValue = new WS.Recomendation.Authentication.ServiceData.GetUserByNameRequest();
            inValue.Body = new WS.Recomendation.Authentication.ServiceData.GetUserByNameRequestBody();
            inValue.Body.name = name;
            return ((WS.Recomendation.Authentication.ServiceData.DataServiceSoap)(this)).GetUserByNameAsync(inValue);
        }
    }
}
